### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by AverageJoe89** [mafredri/electrolux-ocp#1]
Hi,
how could API key be obtained?

**Comment by mafredri** [comment]
Typically the easiest way is to obtain them by packet capture of the Electrolux/AEG app. But you can also find them by searching GitHub, some projects have embedded them. I also have them embedded in another project of mine ([electrolux_exporter/main.go](https://github.com/mafredri/electrolux_exporter/blob/35f81bef7d4ec6c3b977d0db8be06f8608772e66/cmd/electrolux_exporter/main.go)) that uses this library.
